defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

pose:
  data: 'data/motion/Box_3_poses.npz'


model:
  base_model: data/models
  gender: male
  prior: data/prior/gmm_08.pkl
  init_epoch: 50
  epoch: 800
  step_size: 1000
  decay: 0.2
  lr: 0.004
  voxel_size: 0.015
  lambda_prior:
    pose_weight: 0.1
    shape_weight: 0.0001
    strength: 0.01
    patience: 20
    threshold: 1e-1
  sigma: 2
  save_model: True

hydra:
  run:
    dir: .
  output_subdir: null
