model:
  base_model: data/models/basicModel_f_lbs_10_207_0_v1.0.0.pkl
  scan: /home/anthony/Projects/DLHM/data/input/
  prior: data/prior/gmm_08.pkl
  epoch: 120
  step_size: 2500
  decay: 0.2
  lr: 0.04
  voxel_size: 0.015
  lambda_normal: 0.1
  lambda_prior:
    weight: 0.5
    weight_decay: 0.1
    decay_step: 200
  sigma: 2
